"""'admin_role_up'

Revision ID: 47280e80eb55
Revises: da4373d57ab8
Create Date: 2020-05-27 00:46:39.620501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47280e80eb55'
down_revision = 'da4373d57ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
