"""'new'

Revision ID: da4373d57ab8
Revises: 0aacd193b92e
Create Date: 2020-05-26 23:47:02.410470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4373d57ab8'
down_revision = '0aacd193b92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cinema', 'created')
    # ### end Alembic commands ###
